apiVersion: v1
kind: Pod
metadata:
  name: c9s-happy-birthday
  labels:
    c9s: happy-birthday
spec:
  initContainers:
  - name: c9s-happy-birthday-init
    image: kairen/c9s-hb
    command: ["sh", "-c", "cat /c9s.HB.code > /c9s-hb-dir/index.html"]
    volumeMounts:
    - name: c9s-hb-dir
      mountPath: /c9s-hb-dir
  containers:
  - name: c9s-happy-birthday-nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: c9s-hb-dir
      mountPath: /usr/share/nginx/html
  volumes:
  - name: c9s-hb-dir
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: c9s-happy-birthday
  labels:
    c9s: happy-birthday
spec:
  ports:
  - nodePort: 30903
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    c9s: happy-birthday
  type: NodePort
